// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Ukweli.Data;

#nullable disable

namespace Ukweli.Data.Migrations
{
    [DbContext(typeof(UkweliDbContext))]
    [Migration("20260919221958_AddClaimAnalyses")]
    partial class AddClaimAnalyses
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ukweli.Data.Entities.ClaimAnalysis", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<bool>("ActionIsGeneric")
                        .HasColumnType("boolean")
                        .HasColumnName("action_is_generic");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("explanation");

                    b.Property<bool>("IsSeeded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_seeded");

                    b.Property<string>("Jurisdiction")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("jurisdiction");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("model_version");

                    b.Property<string>("NormalizedClaim")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("normalized_claim");

                    b.Property<string>("SeedId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("seed_id");

                    b.Property<string>("SimpleExplanation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("simple_explanation");

                    b.Property<string>("SourceIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("source_ids");

                    b.Property<string>("SourceRelations")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("source_relations");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Unknowns")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("unknowns");

                    b.Property<string>("UserId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_claim_analyses");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("ix_claim_analyses_user_id_created_at");

                    b.ToTable("claim_analyses", (string)null);
                });

            modelBuilder.Entity("Ukweli.Data.Entities.Source", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<DateOnly?>("CheckedAt")
                        .HasColumnType("date")
                        .HasColumnName("checked_at");

                    b.Property<string>("CollectionUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("collection_url");

                    b.Property<string>("Excerpt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("excerpt");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("issuer");

                    b.Property<string>("Jurisdiction")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("jurisdiction");

                    b.Property<bool>("Placeholder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("placeholder");

                    b.Property<DateOnly?>("PublishedAt")
                        .HasColumnType("date")
                        .HasColumnName("published_at");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source_type");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("title");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("topic");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_sources");

                    b.HasIndex("Active", "Jurisdiction", "Topic")
                        .HasDatabaseName("ix_sources_active_jurisdiction_topic");

                    b.ToTable("sources", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
