// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Ukweli.Data;

#nullable disable

namespace Ukweli.Data.Migrations
{
    [DbContext(typeof(UkweliDbContext))]
    partial class UkweliDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ukweli.Data.Entities.Source", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<DateOnly?>("CheckedAt")
                        .HasColumnType("date")
                        .HasColumnName("checked_at");

                    b.Property<string>("CollectionUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("collection_url");

                    b.Property<string>("Excerpt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("excerpt");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("issuer");

                    b.Property<string>("Jurisdiction")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("jurisdiction");

                    b.Property<bool>("Placeholder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("placeholder");

                    b.Property<DateOnly?>("PublishedAt")
                        .HasColumnType("date")
                        .HasColumnName("published_at");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source_type");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("title");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("topic");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_sources");

                    b.HasIndex("Active", "Jurisdiction", "Topic")
                        .HasDatabaseName("ix_sources_active_jurisdiction_topic");

                    b.ToTable("sources", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
